Fix Export Transform Overrides (#USDU-216)
Unity-Technologies/usd-unity-sdk pull request #279
Opened 2021-12-06 21:45 UTC by judubu

## Purpose of this PR

**Ticket/Jira #:** https://jira.unity3d.com/browse/USDU-216

This feature never worked, but there was an example that was exporting overrides properly. 
The use case is that you bring a usd asset in Unity, tweak a bunch of transforms to change the layout, animate a couple of transforms, and you want to export your changes in an override layer. This file should only contain what you changed, nothing else.

This PR fixes override export. You can call it from the USD menu or from use a new option in the USD Recorder window. 

![usd_recorder_export_override](https://user-images.githubusercontent.com/2866068/144927268-df9d5dd7-9aca-4fe3-a288-a7e273a836f5.PNG)

## Testing

**Functional Testing status:**

**Performance Testing status:**

Exporting overrides from recorder is expensive as every xform attributes have to be checked against the original prim

## Overall Product Risks

**Complexity:**

Minimal

**Halo Effect:**

Minimal

## Additional information

**Note to reviewers:**

Reproduction Steps:

- load an usd file
- move one of the imported object
- USD>Export Transform Overrides (usd usda)
- open the exported file, you get all prims exported as override

Desired behavior: you should only get the single xform prim you modified (and its parents) 

**Reminder:**

- [ ] Add entry in CHANGELOG.md _(if applicable)_

2021-12-06 21:51 UTC, judubu commented
@sebastienduverne on the doc review side I just need your approval for the exposed recorder attribute option and the changelog edit.

2021-12-06 21:54 UTC, judubu commented
I noticed the recorder option name appears truncated in the UI. Checking with Vlad offline.

2021-12-06 22:03 UTC, judubu commented on package/com.unity.formats.usd/Runtime/Scripts/Behaviors/UsdAsset.cs
> -                GetFirstPrim(overs).GetReferences().AddReference(rel, GetFirstPrim(baseLayer).GetPath());
@jcowles Do you remember why were adding a relative ref to the original prim? 
My view here is that until we provide tools to target changes to specific layers  I consider the override layer exported from Unity should not reference any other files. Any layering that needs to happen to use the overrides is out of scope and should be done by the user.

Note that I'm also removing the original layer l619

2021-12-07 15:45 UTC, clusty approved these changes

2022-01-04 21:03 UTC, judubu commented
Checked with Vlad, the layout issue is known in the recorder settings.
I shortened the following property labels by removing the Export prefix:
* Export Materials
* Export Transform Overrides

![usd_recorder_export_override_label_fix](https://user-images.githubusercontent.com/2866068/148123635-6bb5d9d7-e775-495d-a6d3-7f937102bbcd.PNG)

@sebastienduverne can you confirm it's allright

2022-01-17 20:56 UTC, cguer approved these changes
QA approved 👍!

Tested on:
- 2021.2.7f1 (Windows only)

----

My only comment is UX-related for the `Transform overrides` option in the Recorder. At first, this looks like an option to "include" additional data in the exported file but it totally changes what will be in the file. For example, enabling this option will not export _anything_ other than the modified values (a user might assume that all objects will still be there). Having a tooltip could help as well to clarify.

There isn't much space but ideally the option we be named something like `Export transform overrides only`. It could even be in a drop-down where users select if they want to export `everything` OR `overrides only`.

Anyways, this is not a blocker for me. Just the kind of comment I would make on a "real" package 😂

2022-01-17 22:08 UTC, cguer requested changes
Oops, I missed something in my previous review. Recording with `Transform Overrides` enabled throws the following exception if the Source is _not_ the root gameobject of an existing USD:
```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Formats.USD.Recorder.UsdRecorderInput.BeginRecording (UnityEditor.Recorder.RecordingSession session) (at Library/PackageCache/com.unity.formats.usd@3559bc2baa00-1642451023084/Editor/Recorder/UsdRecorderInput.cs:18)
UnityEditor.Recorder.Recorder.SignalInputsOfStage (UnityEditor.Recorder.ERecordingSessionStage stage, UnityEditor.Recorder.RecordingSession session) (at Library/PackageCache/com.unity.recorder@4.0.0-pre.2/Editor/Sources/Recorder.cs:299)
UnityEditor.Recorder.RecordingSession.BeginRecording () (at Library/PackageCache/com.unity.recorder@4.0.0-pre.2/Editor/Sources/RecordingSession.cs:152)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

The error is logged if:
- The source is a "normal" gameobject
- The source is a child of a USD root

2023-03-10 12:31 UTC, vickycl reviewed
There's one test failing that I will investigate, but otherwise I've tested the repro and fixed the recorder issue, and I think it's in a good state :)

2023-03-10 12:31 UTC, vickycl commented on package/com.unity.formats.usd/Editor/Recorder/UsdRecorderInput.cs
> +                UsdAsset usdAsset = Settings.GameObject.GetComponentInParent<UsdAsset>(); // Get the UsdAsset component in this GameObject or its nearest parent
@judubu Is this change ok with you?

2023-03-10 15:40 UTC, judubu commented on package/com.unity.formats.usd/Editor/Recorder/UsdRecorderInput.cs
> +                UsdAsset usdAsset = Settings.GameObject.GetComponentInParent<UsdAsset>(); // Get the UsdAsset component in this GameObject or its nearest parent
Looks good. 👍

2023-03-15 14:33 UTC, lee-aandrew commented
Exporting as transform override only saves the changed object and its transform data

Using the Unity Recorder with USD Clip setting "Export X Form Overrides" only record the objects that has its transform changed (Tested both manually changing the transform of objects and running timeline animation)

However, I was also able to reproduce the [error](https://github.com/Unity-Technologies/usd-unity-sdk/pull/279#pullrequestreview-854808058) reported by cguer

2023-03-15 17:46 UTC, lee-aandrew approved these changes
LGTM!

2023-03-15 17:58 UTC, lee-aandrew requested changes
With these changes, the test case ExportSkeletalAnimation_ExportedPrimsHaveSkeletalTypes is failing

2023-03-21 14:37 UTC, vickycl commented on package/com.unity.formats.usd/Runtime/Scripts/Behaviors/UsdAsset.cs
> -                GetFirstPrim(overs).GetReferences().AddReference(rel, GetFirstPrim(baseLayer).GetPath());
Hey @judubu, when exporting the Transform Overrides from the Recorder, we still keep the original scene reference, but we don't here. I don't feel strongly about whether or not we should include the relative ref, but I think they should probably be consistent. Is there some limitation that means for the recorder export we have to include this reference, or something else?

2023-04-05 13:11 UTC, vickycl approved these changes
Looks ready to land to me

2023-04-05 13:19 UTC, cguer approved these changes

2023-04-12 14:35 UTC, michaeljblain requested changes
Looks good. Some minor comments.

2023-04-12 14:35 UTC, michaeljblain commented on package/com.unity.formats.usd/Editor/Recorder/UsdRecorderInput.cs
> +                // this is very brittle- if we have the chance of other sublayers in future we should store the index it was added at and only erase that one.
Do we happen to have this logged as something we should improve?

2023-04-12 14:35 UTC, michaeljblain commented on package/com.unity.formats.usd/Runtime/Scripts/Behaviors/UsdAsset.cs
> +                    overs.Stage.GetRootLayer().GetSubLayerPaths().Erase(0);
Similar to above comment. This may also be considered "brittle".

2023-04-12 14:35 UTC, michaeljblain commented on package/com.unity.formats.usd/Runtime/Scripts/IO/Geometry/XformExporter.cs
> +                    if (Mathf.Abs(sample.transform[i] - sourceSample.transform[i]) > tolerance)
Some concerns how this behaves for large numbers. Maybe we should be considering relative error in this. Is there a library function that can help with this? Maybe we could also add that case to the test.

2023-04-12 15:23 UTC, vickycl commented on package/com.unity.formats.usd/Editor/Recorder/UsdRecorderInput.cs
> +                // this is very brittle- if we have the chance of other sublayers in future we should store the index it was added at and only erase that one.
Added: https://jira.unity3d.com/browse/USDU-362

2023-04-12 15:32 UTC, vickycl commented on package/com.unity.formats.usd/Runtime/Scripts/IO/Geometry/XformExporter.cs
> +                    if (Mathf.Abs(sample.transform[i] - sourceSample.transform[i]) > tolerance)
hmmm interesting point. Theoretically, I think the override should be exported irrelevant of relative scale. For example, if the whole Disney island were moved by half a metre I don't think that should be exported any different to if it was an individual character moving half a metre, even if the relative scales are different. Maybe I'm missing something in how Xforms interact in a hierarchy, though?

2023-04-12 17:13 UTC, michaeljblain approved these changes

2023-04-12 19:41 UTC, lee-aandrew commented
Tested again on Unity 2019.4.26f1
1. Imported Maneki.usd file into Unity
2. Changed "Coin" object by changing its transform values (position & rotation)
3. Exported Transform override as .usda
4. Checked the USDA file only contains the transform changes
5. Manually added the "subLayers" reference to the .usda file
6. Imported the transform override file - the imported file contains the transform changes 👍 

1. Imported Maneki.usd file into Unity
2. Set the Unity Recorder to be USD Clip & Export Transform Override Only
3. Changed "Coin" object by changing its transform values (position & rotation) while the recorder was recording
4. Checked the resulting USDA file only contains the transform changes 👍 
5. Manually added the "subLayers" reference to the .usda file
6. Imported the .usda file into Unity as Timeline Clip
7. Applied the imported Timeline Clip to the original already imported Maneki object - the animation plays 👍 

Checked the test case that was previously failing "ExportSkeletalAnimation_ExportedPrimsHaveSkeletalTypes" is now passing 👍 
Confirmed the 3 new automated test cases are also passing 👍 

LGTM!

2023-04-12 19:42 UTC, lee-aandrew approved these changes

2023-04-13 09:05 UTC, merged