Fixed USDU-173 - scene not marked dirty after changing load payload flag
Unity-Technologies/usd-unity-sdk pull request #322
Opened 2022-11-28 12:33 UTC by mirceaispas

## Purpose of this PR

**Ticket/Jira #:**
https://jira.unity3d.com/browse/USDU-173: Scene is not marked dirty when loading a payload

## Testing

**Functional Testing status:**
Manual tests and automated tests for loading/unloading payloads

**Performance Testing status:**
N/A

## Overall Product Risks

**Complexity:**
Minimal

**Halo Effect:**
Minimal

## Additional information

**Note to reviewers:**

**Reminder:**

- [ ] Add entry in CHANGELOG.md _(if applicable)_

2022-11-30 08:45 UTC, IlliaKo approved these changes
Auto-test looks good. 
Played around fixed case, loading/unloading payloads, looks good :)

2022-12-01 12:39 UTC, vickycl approved these changes
LGTM, nice test coverage :)

2022-12-01 15:37 UTC, mirceaispas commented
Rebased on dev to include CI fixes

2022-12-05 09:05 UTC, michaeljblain requested changes
Looks good to me. Some minor suggestions.

2022-12-05 09:05 UTC, michaeljblain commented on package/com.unity.formats.usd/Tests/Editor/USDPayloadComponentTests.cs
> +        public IEnumerator ChangingUsdPayloadSateFromUnloadedToLoaded_MarksSceneDirty()
Minor typo: Sate -> State

2022-12-05 09:05 UTC, michaeljblain commented on package/com.unity.formats.usd/Tests/Editor/CleanTestEnvironment.cs
> +using NUnit.Framework;
We should add a copyright notice/license at the top of the file.

2022-12-05 10:13 UTC, michaeljblain approved these changes

2022-12-05 10:44 UTC, merged