[Draft] Improve build process docs
Unity-Technologies/usd-unity-sdk pull request #337
Opened 2023-01-18 12:12 UTC by vickycl

## Purpose of this PR

**Ticket/Jira #:**

A draft PR to suggest and discuss some documentation fixes.

## Testing

**Functional Testing status:**

N/A

**Performance Testing status:**

N/A

## Overall Product Risks

**Complexity:** 0

**Halo Effect:** 0

## Additional information

**Note to reviewers:**

**Reminder:**

- [ ] Add entry in CHANGELOG.md _(if applicable)_

2023-01-20 11:41 UTC, SimonBoorer requested changes
You should also update package/com.unity.formats.usd/Documentation~/USD.md with the changes to README.md (up until Licence)

2023-01-27 17:08 UTC, SimonBoorer approved these changes

2023-02-03 11:30 UTC, michaeljblain requested changes
Nice improvements! Some minor suggestions. Otherwise looks good.

2023-02-03 11:30 UTC, michaeljblain commented on BUILDING.md
> +**Unity developers**: USD binaries are built with each new release and pushed on Stevedore. See next section to download them automatically when building the bindings instead of building them.
Might reorder this sentence to:
Instead of building them, see the next section to download them automatically when building the bindings.

2023-02-03 11:30 UTC, michaeljblain commented on README.md
> +To import materials from USD, import the USD file using the USD menu. For the materials to render in the scene, in the Inspector change the Import Settings > Materials to 'Import Preview Surface' and
Very minor suggestion:
To import materials from USD, firstly import the USD file using the USD menu. Then, to get the materials to render in the scene, change the Import Settings > Materials in the Inspector to 'Import Preview Surface'. Finally reimport the USD file.

2023-02-03 11:30 UTC, michaeljblain commented on README.md
> +the inspector on the game object at which these features were authored. Note that Payloads *are not loaded by default*, and USD files using Payloads must be reloaded after changing the Payload Policy
Very minor suggestion:
Note that Payloads *are not loaded by default*. USD files using Payloads must be reloaded after changing the Payload Policy in the Inspector to 'Load All' for them to appear in the Scene.

2023-02-03 11:30 UTC, michaeljblain commented on package/com.unity.formats.usd/Documentation~/USD.md
> +To import materials from USD, import the USD file using the USD menu. For the materials to render in the scene, in the Inspector change the Import Settings > Materials to 'Import Preview Surface' and
See comment above.

2023-02-03 11:30 UTC, michaeljblain commented on package/com.unity.formats.usd/Documentation~/USD.md
> +the inspector on the game object at which these features were authored. Note that Payloads *are not loaded by default*, and USD files using Payloads must be reloaded after changing the Payload Policy
See comment above.

2023-02-03 13:21 UTC, michaeljblain approved these changes

2023-02-07 11:43 UTC, merged