[USDU-280] Reduced the chance of import timing out for complex meshes.
Unity-Technologies/usd-unity-sdk pull request #343
Opened 2023-01-30 16:02 UTC by vickycl

## Purpose of this PR

**Ticket/Jira #:** [USDU-280](https://jira.unity3d.com/browse/USDU-280) / #324

For certain mesh setups (eg where st and normals attributes are of faceVarying interpolation) we have to unweld every face of the mesh to get consistent array sizes. During this sanitization we can timeout and report an error if it takes >1s.

- Increased the timeout on waiting for the read job from 1 second to 10 seconds
- Optimized the Triangulate() function to remove dynamically sized Lists, reducing allocations.

## Testing

**Functional Testing status:**

Tested that the original timeout no longer reproduces.

**Performance Testing status:**

This PR halved the time taken for triangulation in my local testing, profiled with Superluminal:

Before:
![image](https://user-images.githubusercontent.com/45685026/215528463-074ee974-2b02-444c-a9ca-92a91c9f4c8d.png)

After:
![image](https://user-images.githubusercontent.com/45685026/215528650-f9f41651-5440-4928-9dd3-f40238846d52.png)

## Overall Product Risks

**Complexity:** Low

**Halo Effect:** Low

## Additional information

**Note to reviewers:**

@judubu please advise of any further situations I should test?

**Reminder:**

- [x] Add entry in CHANGELOG.md _(if applicable)_

2023-01-30 18:50 UTC, lee-aandrew commented on package/com.unity.formats.usd/Runtime/Scripts/IO/ReadJob.cs
> +                if (!m_ready.WaitOne(10000))
Just a question, is the increase in time out still intentional with the optimization?
If so, is there a need for a discussion on the right value for a time out, and if there is also a need for something like a "cancel import"  button during the import load time?

2023-01-30 19:05 UTC, lee-aandrew commented on package/com.unity.formats.usd/CHANGELOG.md
> +- Optimized triangulation to reduce the chance of a "Timed out while waiting for thread" error on importing a complex mesh.
I did a comparison between the imports pre and post this change, and with my sample file, there was a reduction from 10 seconds to 5 seconds, which seems like a pretty big cut down in time

My test file has:
Batches: 42
Tris: 232.8M
Verts: 116.4M

2023-01-30 20:15 UTC, judubu approved these changes
Awesome gains. Thanks for optimizing.

2023-01-31 09:32 UTC, vickycl commented on package/com.unity.formats.usd/Runtime/Scripts/IO/ReadJob.cs
> +                if (!m_ready.WaitOne(10000))
Yeah, it's still needed. I gambled with 10s being an 'acceptable' timeout given that the Triangulate code is twice as fast. Theoretically a file 20x the size of the repro case will hit this same thing, but given the specific conditions that have triggered it in this case (st and normals set to faceVarying) and the easy workaround for users encountering this in future (increase the timeout) I think this is acceptable _for now_. In future we should definitely look at a more thorough fix, and a cancel option would be very valid. @SimonBoorer mentioned the possibility of using Hydra's triangulate capability, I don't know if that would necessarily be faster but that's a little way off yet.

2023-01-31 14:31 UTC, lee-aandrew commented on package/com.unity.formats.usd/Runtime/Scripts/IO/ReadJob.cs
> +                if (!m_ready.WaitOne(10000))
Thank you for the explanation!

2023-01-31 14:31 UTC, lee-aandrew approved these changes

2023-02-06 13:01 UTC, michaeljblain requested changes
Overall looks good. Some minor suggestions.

2023-02-06 13:01 UTC, michaeljblain commented on package/com.unity.formats.usd/Runtime/Scripts/IO/Geometry/MeshImporter.cs
> +                        int faceCount = usdMesh.originalFaceVertexCounts[faceIndex] - 2;
Super minor: change variable name to faceVertexCount to align with originalFaceVertexCounts

2023-02-06 13:01 UTC, michaeljblain commented on package/com.unity.formats.usd/Runtime/Scripts/IO/SanitizedSamples.cs
> +            if (changeHandedness)
Would be good to state which handedness we're changing from/to

2023-02-06 13:57 UTC, vickycl commented on package/com.unity.formats.usd/Runtime/Scripts/IO/Geometry/MeshImporter.cs
> +                        int faceCount = usdMesh.originalFaceVertexCounts[faceIndex] - 2;
It isn't actually the vertex count, it is the number of faces generated by the triangulation. So for example a quad face (vertexCount = 4) generates 2 triangle faces (vertexCount - 2). I'll change it to  triCount and add a comment :)

2023-02-06 14:28 UTC, michaeljblain commented on package/com.unity.formats.usd/Runtime/Scripts/IO/Geometry/MeshImporter.cs
> +                        int faceCount = usdMesh.originalFaceVertexCounts[faceIndex] - 2;
Ah yes triCount is perfect.

2023-02-06 17:27 UTC, vickycl commented on package/com.unity.formats.usd/Runtime/Scripts/IO/SanitizedSamples.cs
> +            if (changeHandedness)
I added a comment- does it make sense?

2023-02-08 16:15 UTC, michaeljblain commented on package/com.unity.formats.usd/Runtime/Scripts/IO/SanitizedSamples.cs
> +            if (changeHandedness)
Looks good.

2023-02-10 15:27 UTC, michaeljblain approved these changes

2023-02-10 16:24 UTC, merged