Updates Readme.md and Building.md
Unity-Technologies/usd-unity-sdk pull request #356
Opened 2023-03-20 23:09 UTC by lee-aandrew

## Purpose of this PR

Purpose of this PR is to clean up the read me and other documentation in this package

**Ticket/Jira #:**

## Testing

**Functional Testing status:**
N/A

**Performance Testing status:**
N/A

## Overall Product Risks
None 

## Additional information

**Note to reviewers:**

**Reminder:**

- [ ] Add entry in CHANGELOG.md _(if applicable)_

2023-03-21 15:00 UTC, vickycl requested changes
Thanks for the update, I added some comments (I can't see Michael's for some reason, so there may be overlap)

2023-03-21 15:00 UTC, vickycl commented on BUILDING.md
> +Note that currently only Windows, and OSX (Intel CPU) are officially supported.
Please remove the comma too :)

2023-03-21 15:00 UTC, vickycl commented on README.md
> +
I know we talked about including an Implementation Details section at a later date, but I think at the moment this is too thin to be worth it. I'd suggest removing it for this early pass.

2023-03-21 15:00 UTC, vickycl commented on README.md
> +To import a USD file into Unity, use the USD context menu, and select one of the 'Import as ...' options as required
I think we should explicitly talk about the different 'Import as...' options, because they are not clear at first. What each one does, differences in feature sets between importing as GameObjects, Prefabs and Timelines, etc.

2023-03-21 15:00 UTC, vickycl commented on README.md
> +the Timeline window.
If we're numbering steps, Opening the window should be step 1.

2023-03-21 15:00 UTC, vickycl commented on README.md
> +5. Scrubbing through time will now update the USD scene by streaming data from USD.
This isn't a step, so leave it unnumbered. It doesn't make sense to have another number after step 4 saying 'Finally' :P

2023-03-21 15:00 UTC, vickycl commented on README.md
> +If imported USD file is not visible, try re-importing with the 'Load All' Paylaod Policy
Is this line unfinished? I think should be removed

2023-03-21 15:00 UTC, vickycl commented on README.md
> + * .USD
State that our .usd default format is USDC

2023-03-21 18:29 UTC, lee-aandrew commented on README.md
>  The following is a brief listing of currently supported features:
@vickycl @michaeljblain 

I didn't include the "TODO"s listed in the doc: https://docs.google.com/document/d/1Fycd_M3HVwFLhSxfxyZZ79JRjiTXjyOaz6fXqtE7shg/edit#

It didnt seem right to add the todos here, perhaps we could add them under a different section or maybe not include them at all, or add them together with the Unsupported section

let me know what you guys think!

2023-03-21 18:31 UTC, lee-aandrew commented on README.md
> +If imported USD file is not visible, try re-importing with the 'Load All' Paylaod Policy
I changed how this line is worded + added the period at the end, but I think it would be good to state this here, in case people are confused when they see nothing after an import

I know this is repeated in a diff section above, but I think its important enough to state it more than once, in case the reader misses it the first time around

2023-03-21 18:40 UTC, lee-aandrew commented on README.md
> +## Unsupported
Should we have this section?
If so, should we expand it with features that are on the TODO list as well?

2023-03-22 15:20 UTC, lee-aandrew commented on README.md
> +## Unsupported
As per our chat in the Google docs features list, I've added the Unsupported section here!

2023-03-22 15:20 UTC, lee-aandrew commented on README.md
>  The following is a brief listing of currently supported features:
As per our chat in the Google docs features list, I've added the Unsupported section here!
https://docs.google.com/document/d/1Fycd_M3HVwFLhSxfxyZZ79JRjiTXjyOaz6fXqtE7shg/edit#

2023-04-13 14:40 UTC, vickycl approved these changes
Thanks! :)

2023-04-13 14:57 UTC, lee-aandrew commented
Thanks for the reviews @vickycl

2023-04-13 14:57 UTC, merged